language: rust

rust: nightly

env:
  global:
    - secure: dmTlUsfGIwrpcY7QWu1d+YiCiGvwMgUjrorAIDTKBtYivmaSEwLqm1O7n+7aHks+j5Xy6eXfBJwpv0xsiutDeEW0h7KDlqKF2MnRTY/tPgr1W9n0x9mAHizB+473MprmTLKObsrU5HFNIK20W31Nz9HGCYPN/Cxq3RaWGpfyU2Q=

after_script:
  - cargo doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

before_script:
  - cargo update
