language: rust

rust: nightly

env:
  global:
    - secure: eSpHGxGT3pFxoWK9ov8IOFdZrfVUUnjsFDU/t5ILWGXj9sL3Uek/kkYn1fYB8HWKWBtvh9PeyoU/GIbczmBPEhali97NMIQvwM/sznkVyQtfxOAbvQ0bbXjmdrKIgyVc2TRfz1fBESui9ejexcZYkr56ywpCljFhg4LJ8U7ZK5E=

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

