[package]

name = "phant"
version = "0.1.2"
authors = [ "ethan.frei@gmail.com" ]
description = "A library for manipulating data on a http://phant.io server."

documentation = "http://static.ethanfrei.com/phant/phant"
homepage = "https://github.com/freiguy1/phant-rust"
repository = "https://github.com/freiguy1/phant-rust"
readme = "README.md"
keywords = ["phant", "sparkfun"]
license = "MIT"

[lib]

name = "phant"
path = "src/lib.rs"

[dependencies]
url = "*"
hyper = "*"
serde = "*"
serde_json = "*"
