[package]

name = "phant"
version = "0.0.4"
authors = [ "ethan.frei@gmail.com" ]
description = "A library for manipulating data on a http://phant.io server."

documentation = "http://www.rust-ci.org/freiguy1/phant-rust/doc/phant/"
homepage = "https://github.com/freiguy1/phant-rust"
repository = "https://github.com/freiguy1/phant-rust"
readme = "README.md"
keywords = ["phant", "sparkfun"]
license = "MIT"

[lib]

name = "phant"
path = "src/lib.rs"

[dependencies]
url = "*"
