[package]

name = "phant"
version = "0.1.4"
authors = [ "ethan.frei@gmail.com" ]
description = "A library for manipulating data on a http://phant.io server."

documentation = "http://static.ethanfrei.com/phant/phant"
homepage = "https://github.com/freiguy1/phant-rust"
repository = "https://github.com/freiguy1/phant-rust"
readme = "README.md"
keywords = ["phant", "sparkfun"]
license = "MIT"

[lib]

name = "phant"
path = "src/lib.rs"

[dependencies]
url = "1.1.1"
hyper = "0.9.9"
serde = "0.7.10"
serde_json = "0.7.1"
